### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by a-v-s** [diegoherranz/PIC-USB-CDC#1]
The project does not build using 3.9.0. See the attached log file 
[build_log.txt](https://github.com/diegoherranz/PIC-USB-CDC/files/3194578/build_log.txt)

**Comment by diegoherranz** [comment]
Sorry I had missed this message. I only cloned this repo from Kustaa Nyholm.
It's not actually my code, and haven't used it.
In fact, I'll just close this repo to avoid confusion.
Thanks.

**Comment by diegoherranz** [comment]
See http://www.sparetimelabs.com/usbcdcacm/usbcdcacm.php for the original source and more info.
